name: Convert LaTeX to Markdown

on:
  push:
    paths:
      - '**.tex'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Pandoc
      run: sudo apt-get update && sudo apt-get install -y pandoc

    - name: Run LaTeX to Markdown converter
      run: |
        chmod +x .github/scripts/convert.sh
        .github/scripts/convert.sh

    - name: List output files
      run: |
        echo "Generated Markdown files:"
        ls -la output/ || echo "No output directory found"

    - name: Commit and push results
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add output/*.md
        git commit -m "Auto-convert LaTeX to Markdown" || echo "Nothing to commit"
        git push
