name: Convert LaTeX to Markdown

on:
  push:
    paths:
      - '**.tex'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y pandoc python3

      - name: Make script executable
        run: chmod +x convert.sh

      - name: Run conversion script
        run: ./convert.sh

      - name: List output files
        run: ls -la output/

      - name: Commit and push results
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add output/*.md
          git commit -m "Auto-convert LaTeX to Markdown" || echo "Nothing to commit"
          git push