#!/bin/bash
name: Convert LaTeX to Markdown and Split by Section

on:
  push:
    paths:
      - '**.tex'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Delete old Markdown output
        run: rm -rf output && mkdir -p output

      - name: Convert full documents to clean Markdown
        run: |
          # Function to clean up LaTeX artifacts
          clean_markdown() {
            local file="$1"
            # Remove escaped backslashes from headers
            sed -i 's/\\#/#/g' "$file"
            sed -i 's/\\\*/*/g' "$file"
            sed -i 's/\\_/_/g' "$file"
            # Remove any lines that start with # (all headers)
            sed -i '/^#.*$/d' "$file"
            # Remove footnote references and content
            sed -i 's/\[^[0-9]*\]//g' "$file"
            sed -i '/^\[^[0-9]*\]:/d' "$file"
            # Fix double spaces and improve paragraph spacing
            sed -i 's/  \+/ /g' "$file"
            sed -i 's/\n\n\n\+/\n\n/g' "$file"
            # Remove leading/trailing whitespace
            sed -i 's/^[[:space:]]*//' "$file"
            sed -i 's/[[:space:]]*$//' "$file"
          }
          
          # Convert full documents to clean Markdown (without headers)
          find . -maxdepth 1 -name "*.tex" -not -name "Full Doc.tex" | while read -r tex_file; do
            base_name=$(basename "$tex_file" .tex)
            echo "Converting full document: $tex_file"
            
            # Convert to markdown using improved pandoc options
            pandoc -f latex -t markdown --wrap=auto --columns=120 --markdown-headings=atx --standalone "$tex_file" -o "output/${base_name}.md"
            
            if [ $? -eq 0 ]; then
              # Clean up the generated markdown to remove headers
              clean_markdown "output/${base_name}.md"
              echo "Created clean full document: output/${base_name}.md"
            fi
          done

      - name: Find TeX files
        run: |
          find . -maxdepth 1 -name "*.tex" -not -name "Full Doc.tex" > tex_list.txt
          cat tex_list.txt

      - name: Convert TeX files to Markdown and split by section
        run: |
          today=$(date +%F)
          
          # Function to clean up LaTeX artifacts
          clean_markdown() {
            local file="$1"
            # Remove escaped backslashes from headers
            sed -i 's/\\#/#/g' "$file"
            sed -i 's/\\\*/*/g' "$file"
            sed -i 's/\\_/_/g' "$file"
            # Remove any lines that start with # (all headers)
            sed -i '/^#.*$/d' "$file"
            # Remove footnote references and content
            sed -i 's/\[^[0-9]*\]//g' "$file"
            sed -i '/^\[^[0-9]*\]:/d' "$file"
            # Fix double spaces and improve paragraph spacing
            sed -i 's/  \+/ /g' "$file"
            sed -i 's/\n\n\n\+/\n\n/g' "$file"
            # Remove leading/trailing whitespace
            sed -i 's/^[[:space:]]*//' "$file"
            sed -i 's/[[:space:]]*$//' "$file"
          }
          
          while IFS= read -r tex_file; do
            [ ! -f "$tex_file" ] && echo "Skipping invalid file: $tex_file" && continue
            echo "Processing $tex_file"
            base_name=$(basename "$tex_file" .tex)

            # Get chapter title
            chapter_title=$(grep '\\chapter{' "$tex_file" | head -1 | sed 's/.*\\chapter{//;s/}.*//')
            chapter_title_clean=$(echo "$chapter_title" | tr -cd '[:alnum:] .:/-' | sed 's/["\\]/ /g')
            slug=$(echo "$chapter_title_clean" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | sed 's/^-\|-$/-/g')

            # Create intro file
            intro_lines=$(awk '/\\section\{/{exit} {print}' "$tex_file" | sed 's/\\chapter{.*}//' | sed 's/^[[:space:]]*//')
            {
              echo "---"
              echo "title: \"$chapter_title_clean\""
              echo "slug: \"$slug\""
              echo "publishDate: \"$today\""
              echo "chapter: \"$chapter_title_clean\""
              echo "section: \"$chapter_title_clean\""
              echo "parentSlug: \"$slug\""
              echo "order: 0"
              echo "toc: true"
              echo "description: \"\""
              echo "draft: false"
              echo "---"
              echo ""
              echo "$intro_lines" | pandoc -f latex -t gfm --wrap=none --markdown-headings=atx --standalone
            } > "output/${base_name}_intro.md"
            clean_markdown "output/${base_name}_intro.md"
            echo "[INFO] Created intro: output/${base_name}_intro.md"

            # Split sections
            awk -v base="$base_name" -v parent="$slug" -v chapter="$chapter_title_clean" -v today="$today" '
              BEGIN { filecount = 1; in_section = 0; section_title = ""; section_content = "" }
              /^\\section\{/ {
                if (in_section && section_title != "") { save_section() }
                in_section = 1
                section_title = substr($0, 10)
                section_title = substr(section_title, 1, index(section_title, "}") - 1)
                section_content = ""
                next
              }
              in_section {
                if (section_content == "") {
                  section_content = $0
                } else {
                  section_content = section_content "\n" $0
                }
              }
              END { if (in_section && section_title != "") { save_section() } }
              function save_section() {
                gsub(/[[:space:]]+$/, "", section_title)
                gsub(/\\\\/, "", section_title)
                gsub(/"/, "", section_title)
                gsub(/[^[:alnum:] .:-]/, "", section_title)
                slugified = tolower(section_title)
                gsub(/[^a-z0-9]+/, "-", slugified)
                gsub(/^-|-$/, "", slugified)
                outname = "output/" base "_section_" filecount ".md"
                temp_file = "temp_section_" filecount ".tex"
                print section_content > temp_file
                if (system("test -s " temp_file) == 0) {
                  print "---" > outname
                  print "title: \"" section_title "\"" >> outname
                  print "slug: \"" slugified "\"" >> outname
                  print "publishDate: \"" today "\"" >> outname
                  print "chapter: \"" chapter "\"" >> outname
                  print "section: \"" section_title "\"" >> outname
                  print "parentSlug: \"" parent "\"" >> outname
                  print "order: " filecount >> outname
                  print "toc: true" >> outname
                  print "description: \"\"" >> outname
                  print "draft: false" >> outname
                  print "---" >> outname
                  print "" >> outname
                  cmd = "pandoc -f latex -t markdown --wrap=auto --columns=120 --markdown-headings=atx --standalone " temp_file " >> " outname
                  system(cmd)
                  print "[INFO] Created section: " outname > "/dev/stderr"
                  filecount++
                } else {
                  print "[WARN] Skipping empty section for: " section_title > "/dev/stderr"
                }
                system("rm -f " temp_file)
              }
            ' "$tex_file"
          done < tex_list.txt
          
          # Clean up all generated markdown files
          echo "Cleaning up markdown files..."
          for file in output/*.md; do
            if [ -f "$file" ]; then
              clean_markdown "$file"
              echo "Cleaned: $file"
            fi
          done

      - name: List output files
        run: ls -la output/ || echo "No output directory found"

      - name: Commit and push results
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add output/*.md
          git commit -m "Auto-convert LaTeX to Markdown and split by section" || echo "Nothing to commit"
          git push